server:
  port: 8080
  servlet:
    context-path: /iCommerce

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: jdbc:mysql://localhost:3306/cosmetic
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
      minimum-idle: 100
      idle-timeout: 300000000
      max-lifetime: 1800000000
      connection-timeout: 200000000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        flushMode: COMMIT

  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

  mail:
    host: smtp.gmail.com
    port: 587
    username: pghuy2101320@student.ctuet.edu.vn
    password: sogmayxdddclcqpf   # Không có dấu ngoặc kép và khoảng trắng
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com


jwt:
  signerKey: "AHbWXn6k9g06iFIaGiCfgCw4QzfQO/AdcNC30hBhLxmhwUyf6bE+7o2UMUrp06K4"
  valid-duration: 3600
  refreshable-duration: 36000

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

momo:
  partner-code: MOMO
  return-url: http://localhost:3000/momo-return
  end-point: https://test-payment.momo.vn/v2/gateway/api/create
  ipn-url: http://localhost:8080/iCommerce/api/momo/ipn-handler
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  request-type: captureWallet
