server:
  port: 8080
  servlet:
    context-path: /iCommerce



spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/iCommerce"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  signerKey: "AHbWXn6k9g06iFIaGiCfgCw4QzfQO/AdcNC30hBhLxmhwUyf6bE+7o2UMUrp06K4"
  valid-duration: 3600 #second
  refreshable-duration: 36000 #second


