server:
  port: 8080
  servlet:
    context-path: /iCommerce
    multipart:
      enabled: true # Bật tính năng multipart (upload file)
      max-file-size: 2000MB  # Giới hạn kích thước tối đa của file là 20MB
      max-request-size: 2000MB




spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/iCommerce"
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
      minimum-idle: 100
      idle-timeout: 300000000
      max-lifetime: 1800000000
      connection-timeout: 200000000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/



jwt:
  signerKey: "AHbWXn6k9g06iFIaGiCfgCw4QzfQO/AdcNC30hBhLxmhwUyf6bE+7o2UMUrp06K4"
  valid-duration: 3600 #second
  refreshable-duration: 36000 #second

logging:
  level:
    org.springframework.web: DEBUG # Cấu hình log mức độ DEBUG cho Spring Web



